### PR TITLE
Update quoter.plugin.js

### PR DESCRIPTION
**Pull request by SaschaP1802**
Disable Contextmenu

### CODE REVIEW

**Comment by rauenzi** [comment]
Why?

**Comment by SaschaP1802** [comment]
> Why?

So you can use it with 305!

**Comment by SaschaP1802** [comment]
> > Why?
> 
> So you can use it with 305!

http://prntscr.com/mypjq9

**Comment by rauenzi** [comment]
The effort would be better spent fixing the issue rather than removing the feature

**Comment by SaschaP1802** [comment]
> The effort would be better spent fixing the issue rather than removing the feature

Well then you could do it, I do not have the idea of it. Therefore, I have disabled the faulty option. to continue to use the plugin, and shared it.

**Comment by rauenzi** [comment]
I will fix it when I have free time, yes.

**Comment by SaschaP1802** [comment]
allright thx for that

**Pull request closed without merging**
